backend:
  name: git-gateway
  branch: main
collections:
  - name: routes
    label: routes
    folder: src/routes
    create: true
    fields:
      - name: title
      - name: nav_label
      - name: body
        widget: markdown
media_folder: "static/uploads"
public_folder: "/uploads"

site_url: https://hcg.org.nz
display_url: https://hcg.org.nz
logo_url: https://hcg.org.nz/images/uploads/gnz.png